version: '3'
services:
  web:
    build: .

    # comment others and uncomment below for -it
    # entrypoint: /bin/sh
    # tty: true
    # stdin_open: true

    # comment others and uncomment below on first run
    # command: npm install

    # comment others and uncomment below for next runs
    command: npm run dev  

    # uncomment below and comment above to add dependancy
    # command: npm install --save axios  
    volumes:
      - ./usr/app/:/usr/app/
    ports:
      - "3333:3333"
    # depends_on:
    #   - postgres
  #   environment:
  #     DATABASE_URL: postgres://todoapp@postgres/todos
  # postgres:
  #   image: postgres:9.6.2-alpine
  #   environment:
  #     POSTGRES_USER: todoapp
  #     POSTGRES_DB: todos